### ISSUE TITLE
Not working with activerecord relations

### ISSUE THREAD

**Issue by dkumar431** [anjlab/db-switch#1]
After a lot of search i found your gem for switching db connections for my slave database. But it does not seems to be working properly

Here is an example,

`ActiveRecord::Base.connect_to(:replica_one) do
   User.first
end`

The above one works fine. But the below does not works. Not sure but all similar gems like octopus and others also have the same issue.

`ActiveRecord::Base.connect_to(:replica_one) do
    User.where(id: 1)
end`

Any help would be greatly appreciated..

**Comment by serggl** [comment]
@dkumar431 the above actually works fine for me (Rails 5)
```
[8] pry(main)> User.where(id: 1).pluck :id, :first_name, :last_name
=> [[1, "Hub", "Manager"]]
```

```
[9] pry(main)> ActiveRecord::Base.connect_to(:replica_one) {  User.where(id: 1).pluck :id, :first_name, :last_name }
=> [[1, "System Administrator", "User"]]
```

Which Rails version are you testing with. Could be this a setup issue?

**Comment by dkumar431** [comment]
@serggl 

I found the cause of my issue, 

This does not work ,

`ActiveRecord::Base.connect_to(:replica_one) do User.where(id: 1) end`

When i changed it to,

`ActiveRecord::Base.connect_to(:replica_one) do User.where(id: 1).to_a end`

It started working fine. 

So if you just run `User.where(id: 1)` it never works . Even with octopus also.

**Comment by serggl** [comment]
@dkumar431 now I understand. Let me see what could be done here

**Comment by serggl** [comment]
@dkumar431 I think this is happening because you return a lazy-loaded relation from the `connect_to` block. In this case actual querying happen with the default connection parameters.
So I assume this is an expected behaviour

**Comment by apayden** [comment]
@serggl Is there a workaround for this?  There's a lot of functionality that is lost when we have to switch from an ActiveRecord::Relation to an Array.
